/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDatasetRouteImport } from './routes/api/public/dataset'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicScrapeRouteImport } from './routes/api/public/scrape'
import { Route as ApiPublicTokensRouteImport } from './routes/api/public/tokens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDatasetRoute = ApiPublicDatasetRouteImport.update({
  id: '/api/public/dataset',
  path: '/api/public/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScrapeRoute = ApiPublicScrapeRouteImport.update({
  id: '/api/public/scrape',
  path: '/api/public/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTokensRoute = ApiPublicTokensRouteImport.update({
  id: '/api/public/tokens',
  path: '/api/public/tokens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/dataset': typeof ApiPublicDatasetRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
  '/api/public/tokens': typeof ApiPublicTokensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/dataset': typeof ApiPublicDatasetRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
  '/api/public/tokens': typeof ApiPublicTokensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/dataset': typeof ApiPublicDatasetRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
  '/api/public/tokens': typeof ApiPublicTokensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/dataset'
    | '/api/public/ingest'
    | '/api/public/scrape'
    | '/api/public/tokens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/dataset'
    | '/api/public/ingest'
    | '/api/public/scrape'
    | '/api/public/tokens'
  id:
    | '__root__'
    | '/'
    | '/api/public/dataset'
    | '/api/public/ingest'
    | '/api/public/scrape'
    | '/api/public/tokens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDatasetRoute: typeof ApiPublicDatasetRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicScrapeRoute: typeof ApiPublicScrapeRoute
  ApiPublicTokensRoute: typeof ApiPublicTokensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dataset': {
      id: '/api/public/dataset'
      path: '/api/public/dataset'
      fullPath: '/api/public/dataset'
      preLoaderRoute: typeof ApiPublicDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrape': {
      id: '/api/public/scrape'
      path: '/api/public/scrape'
      fullPath: '/api/public/scrape'
      preLoaderRoute: typeof ApiPublicScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tokens': {
      id: '/api/public/tokens'
      path: '/api/public/tokens'
      fullPath: '/api/public/tokens'
      preLoaderRoute: typeof ApiPublicTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDatasetRoute: ApiPublicDatasetRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicScrapeRoute: ApiPublicScrapeRoute,
  ApiPublicTokensRoute: ApiPublicTokensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
